### ISSUE TITLE
minus sign not cleared when writing 3 digit values

### ISSUE THREAD

**Issue by KenT2** [pimoroni/fourletter-phat#8]
Using write_number_str and writing -3.25  (or any other -ve number) followed by 3.26 (or any other +ve number) the minus sign is not cleared.

Workaround is to clear the display before a write.

**Comment by Gadgetoid** [comment]
I've come across this before, and am wary to change the interface, but I think in all cases `write_number_str` should either clear the display or fill in unused characters with blanks to avoid this.

**Comment by Gadgetoid** [comment]
Yep, looks like this has already been ported over from Rainbow HAT I believe, and fixed in this commit: https://github.com/pimoroni/fourletter-phat/commit/af726cd6fae2a12d9ad394817289d559af18f132

It just hasn't found its way to a release yet.

**Comment by Gadgetoid** [comment]
Should be fixed in: https://github.com/pimoroni/fourletter-phat/releases/tag/v0.1.0
